module.exports = [
  {label: '体育迷', id: '001'},
  {label: '段子手', id: '002'},
  {label: '养生堂', id: '003'},
  {label: '私房话', id: '004'},
  {label: '八卦精', id: '005'},
  {label: '爱生活', id: '006'},
  {label: '财经迷', id: '007'},
  {label: '汽车米', id: '008'},
  {label: '科技咖', id: '009'},
  {label: '潮人版', id: '010'},
  {label: '辣妈帮', id: '011'},
  {label: '军事', id: '012'},
  {label: '旅行家', id: '013'},
  {label: '职场人', id: '014'},
  {label: '美食家', id: '015'},
  {label: '古今通', id: '016'},
  {label: '学霸族', id: '017'},
  {label: '星座控', id: '018'},
  {label: '热点', id: '019'},
]
